spring:
  profiles:
    active: local
  config:
    import:
      - classpath:application-key.yml
      - optional:file:/home/ubuntu/application-key.yml
      - optional:file:./application-key.yml

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:5173/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: a1f7d23c8e56b9f1840f7a9b9f4c3b579a3d8f2e648cbe7398cdd249e2f4baf52c3678e1054f3e1e0aa6e1db4523e07f
  access:
    header: Authorization

  refresh:
    header: Authorization-Refresh

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-doc

tmdb:
  api:
    # TMDB API 키
    key: ${tmdb.api.key}
    # TMDB 베이스 URL
    base-url: https://api.themoviedb.org/3
    # 응답 언어 설정 (한국어)
    language: ko-KR
  image:
    base-url: https://image.tmdb.org/t/p/
    poster-size: w500

kobis:
  api:
    #영화진흥원 API 키
    key: ${kobis.api.key}
    # 베이스 URL
    base-url: http://www.kobis.or.kr/kobisopenapi/webservice/rest

scheduler:
  cron:
    daily: "0 0 1 * * ?"
    weekly: "0 0 2 ? * MON"
    request_movie: "0 0 4 * * *"
  zone: "Asia/Seoul"

movie:
  seed-enabled: false # 시딩 끝나면 false
  update-enabled: true #시딩 끝나면 true


