spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/v1/member/kakao-accesstoken
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: a1f7d23c8e56b9f1840f7a9b9f4c3b579a3d8f2e648cbe7398cdd249e2f4baf52c3678e1054f3e1e0aa6e1db4523e07f
  access:
    header: Authorization

  refresh:
    header: Authorization-Refresh

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-doc

tmdb:
  api:
    # TMDB API 키
    key: ${TMDB_API_KEY}
    # TMDB 베이스 URL
    base-url: https://api.themoviedb.org/3
    # 응답 언어 설정 (한국어)
    language: ko-KR

kobis:
  api:
    #영화진흥원 API 키
    key: ${KOBIS_API_KEY}
    # 베이스 URL
    base-url: http://www.kobis.or.kr/kobisopenapi/webservice/rest