name: Auto Close Issues on dev merge

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Close linked issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prBody = context.payload.pull_request.body;
            const issuePattern = /(?:Closes|Fixes|Resolves) #(\d+)/gi;
            let match;

            while ((match = issuePattern.exec(prBody)) !== null) {
              const issue_number = parseInt(match[1]);
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                state: 'closed'
              });
              console.log(`Closed issue #${issue_number}`);
            }